### ISSUE TITLE
Dockerize the Django app.

### ISSUE THREAD

**Issue by jastr945** [eputnam/latrine#37]
Create a ```Dockerfile``` for the Django app (development mode).

**Comment by jastr945** [comment]
Submitted a PR and noticed that @jrp114's Dockerfile was already merged. Thanks for another PR! A small request: please let everyone know in the comment section that you plan to work on something before submitting the code - that would help us avoid conflicts. Or you can just assign yourself to an issue.

The Dockerfile looks alright, however, the image turned out to be too large. This is because our React app was copied into it, along with many other unnecessary files. We should use CMD to pass and automate all of our python management commands, instead of ENTRYPOINT. We should also specify the version of the python base image, which is considered to be a good practice.

@maryannet , @jrp114 , could you both have a look at my PR #40 and see how we can reach a compromise?

**Comment by jrp114** [comment]
Thanks! I'll make a comment or assign myself an issue next time before submitting a PR. #40 looks good to me to use here.
